language: python
environment:
  COVERAGE_PROCESS_START: 1

dist: bionic
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - python -c'import sys; print(sys.path)'
  - exit 1
  - pip install --quiet coverage flake8 wheel pandoc httpie

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
