language: python
environment:
  COVERAGE_PROCESS_START: 1

dist: bionic
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - echo 'import coverage; coverage.process_startup()' > sitecustomize.py
  - echo 'import coverage; coverage.process_startup()' > test/sitecustomize.py
  - pip install --quiet coverage flake8 wheel pandoc httpie

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
